spring:
    application:
        name: xgn-console
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            show-sql: true
            ddl-auto: update
    redis:
        host: 192.168.0.97
        port: 6379
server:
    context-path: /console
    port: 9001