spring:
    application:
        name: xgn-console
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.0.97:5432/demo
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    redis:
        host: 192.168.0.97
        port: 6379
server:
    context-path: /console
    port: 9001