import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'YaFengLi' at '16-11-16 下午3:23' with Gradle 3.2
 *
 * @author YaFengLi, @date 16-11-16 下午3:23
 */
public class DemoTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
