spring:
    application:
        name: ftl_spring_boot_demo
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password:
        hikaricp:
          dataSourceClassName: org.h2.jdbcx.JdbcDataSource
          maximumPoolSize: 20
          idleTimeout: 30000
    freemarker:
        suffix: .ftl
        charset: utf-8
        cache: true
        expose-request-attributes: true
        request-context-attribute: request
server:
    context-path: /server
    port: 8000
