= Hello World
Doc Writer<yafengli@sina.com>
v1.0, 2014-01-01
:toc:

== http://asciidoc.org[AsciiDoc]
* 生成HTML文档

    $ asciidoctor README.adoc

* 生成PDF文档

    $ asciidoctor-pdf README.adoc


== Java
* 程序

.Hello.java
[source,java]
----
import java.util.*;
public class Hello {                       // <1>
  public static void main(String[] args){  // <2>
    System.out.println("Hello World!");    // <3>
  }
}
----
<1> Class Name
<2> Method Name
<3> Program Process

== Scala
* 程序

.Test.scala
[source, scala]
----
import scala.io.Source
Source.fromFile("/tmp/demo.txt").getLines.toStream.foreach(println(_))
----

[verse, William Blake, from Auguries of Innocence]
To see a world in a grain of sand,
And a heaven in a wild flower,
Hold infinity in the palm of your hand,
And eternity in an hour.

[verse, YaFengLi, from the Republic of Chinese]
To see a world in a grain of sand,
And a heaven in a wild flower,
Hold infinity in the palm of your hand,
And eternity in an hour.

[literal]
Consul *necessitatibus* per id,
consetetur, eu pro everti postulant
homero verear ea mea, qui.

.test.c
[source,c]
----
#include <stdio.h>

int main() {
   printf("Hello World!\n");
   exit(0);
}
----

[subs="quotes"]
++++
<table border="1"><tr>
  <td>*Cell 1*</td>
  <td>*Cell 2*</td>
</tr></table>
++++

.An example
====
Qui in magna commodo, est labitur dolorum an. Est ne magna primis
adolescens.

  hello

  world

====

[listing]
--
Lorum ipsum ...
--
---------------
Lorum ipsum ...
---------------

- List item.
* List item.
** List item.
** List item.
*** List item.
*** List item.
**** List item.
**** List item.
***** List item.
***** List item.

== Nice

. Arabic (decimal) numbered list item.
.. Lower case alpha (letter) numbered list item.
... Lower case roman numbered list item.
.... Upper case alpha (letter) numbered list item.
..... Upper case roman numbered list item.


Main Header
===========
Optional Author Name <optional@author.email>
Optional version, optional date

:Author:    YaFengLi
:Email:     <yafengli@sina.com>
:Date:      2014-11-12 12:00
:Revision:  1.2.5
:MyName:  李亚峰

Attributes

* Author is {Author}
* Email is {Email}
* Date is {Date}
* Revision is {Revision}
* My Name is {MyName}

Literal paragraph.
  Must be indented.

.test.pl
[source,perl]
die 'connect: '.$dbh->errstr;

NOTE: This is an example
      single-paragraph note.

TIP: This is an example
      single-paragraph note.

IMPORTANT: Hello World!
      is nice programming example!

WARNING: Hello World!
      is nice programming example!

CAUTION: Hello World!
      is nice programming example!


[NOTE]
====
*NOTE* Block
Use: multi-paragraph notes.

.hello.cpp
[source,c]
----
#include <stdio.h>
int main(int argc,char * argv[]){
  return 0;
}
----
====


Level 1
-------
Text.

Level 2
~~~~~~~
Text.

Level 3
^^^^^^^
Text.

Level 4
+++++++
Text.

== Level 1
Text.

=== Level 2
Text.

==== Level 3
Text.

===== Level 4
Text.
