import com.google.common.primitives.Bytes;
import demo.security.DigestUtils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        byte[] bytes = new String("hello").getBytes();

        System.out.println("[hello] md5:" + DigestUtils.encodeMD5Hex(bytes));


        byte[] cs = DigestUtils.encodeMD5(bytes);

        Bytes.asList(cs).forEach(t -> System.out.print(Integer.toHexString(t & 0xFF)));
        System.out.println();
        System.out.println(toHex(cs));
    }

    public static String toHex(byte[] bytes) {
        StringBuilder builder = new StringBuilder();
        Bytes.asList(bytes).forEach(t -> builder.append(Integer.toHexString(t & 0xFF)));
        return builder.toString();
    }
}
